server:
  port: 8080

spring:
  datasource:
    username: ${RDB_USERNAME}
    url: ${RDB_URL}
    password: ${RDB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}

  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    database-platform: org.hibernate.dialect.MySQL8Dialect
    open-in-view: false

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.timeout: 5000


exclude-auth-path-patterns:
  paths:
    - path-pattern: /api/users/sign-up
      method: POST
    - path-pattern: /api/users/login
      method: POST
    - path-pattern: /api/email/send
      method: POST
    - path-pattern: /api/email/verify
      method: POST
    - path-pattern: /swagger-ui.html
      method: GET
    - path-pattern: /swagger-ui/index.html
      method: GET
    - path-pattern: /swagger-ui/**
      method: GET
    - path-pattern: /v3/api-docs
      method: GET
    - path-pattern: /v3/api-docs/swagger-config
      method: GET
    - path-pattern: /webjars
      method: GET
    - path-pattern: /actuator/health/**
      method: GET

exclude-blacklist-path-patterns:
  paths:
    - path-pattern: /api/users/sign-up
      method: POST
    - path-pattern: /api/users/login
      method: POST
    - path-pattern: /api/email/send
      method: POST
    - path-pattern: /api/email/verify
      method: POST
    - path-pattern: /swagger-ui.html
      method: GET
    - path-pattern: /swagger-ui/index.html
      method: GET
    - path-pattern: /swagger-ui/**
      method: GET
    - path-pattern: /v3/api-docs
      method: GET
    - path-pattern: /v3/api-docs/swagger-config
      method: GET
    - path-pattern: /webjars
      method: GET
    - path-pattern: /actuator/health/**
      method: GET

exclude-whitelist-path-patterns:
  paths:
    - path-pattern: /api/users/sign-up
      method: POST
    - pathPattern: /api/users/login
      method: POST
    - path-pattern: /api/users/logout
      method: DELETE
    - path-pattern: /api/token/reissue
      method: POST
    - path-pattern: /api/email/send
      method: POST
    - path-pattern: /api/email/verify
      method: POST
    - path-pattern: /swagger-ui.html
      method: GET
    - path-pattern: /swagger-ui/index.html
      method: GET
    - path-pattern: /swagger-ui/**
      method: GET
    - path-pattern: /v3/api-docs
      method: GET
    - path-pattern: /v3/api-docs/swagger-config
      method: GET
    - path-pattern: /webjars
      method: GET
    - path-pattern: /actuator/health/**
      method: GET

jwt-properties:
  key: ${JWT_KEY:KItFWMZokpiSj6ABi42XJpNWbBqUJ4UT3mhLrXk//IjI2TgQy2Bk+2KrCk4cQDl8oFsSYH9Gr++Lqr2w6CYJnQ==}
  access-token-expiration-period-day: 1
  access-token-subject: AccessToken
  refresh-token-expiration-period-day: 30
  refresh-token-subject: RefreshToken
  token-header: Authorization
  bearer: Bearer
  id: id

logging:
  level:
    root: INFO
    org.springframework: DEBUG
    org.springframework.web: DEBUG
    org.springframework.boot: DEBUG
    com.project.user: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    groups-order: DESC
    tags-sorter: alpha
    operations-sorter: method
    enabled: true
  paths-to-match:
    - /api/**