name: User Service CI/CD (GCP)

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: asia-northeast3
  REPO: microservices
  IMAGE: user-service

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build
        run: ./gradlew build -x test

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Configure Docker auth for Artifact Registry
        run: gcloud auth configure-docker ${REGION}-docker.pkg.dev --quiet

      - name: Build and push image
        run: |
          TAG=${{ github.sha }}
          IMAGE_URI=${REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${REPO}/${IMAGE}
          docker build -t ${IMAGE_URI}:${TAG} -t ${IMAGE_URI}:latest .
          docker push ${IMAGE_URI}:${TAG}
          docker push ${IMAGE_URI}:latest

      - name: Open PR to infra repo with new image tag
        if: github.ref == 'refs/heads/main'
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          INFRA_REPO: ${{ secrets.INFRA_REPO }}
          REGION: ${{ env.REGION }}
          GCP_PROJECT_ID: ${{ env.GCP_PROJECT_ID }}
          REPO: ${{ env.REPO }}
          IMAGE: ${{ env.IMAGE }}
        run: |
          set -e
          git config --global user.email "action@github.com"
          git config --global user.name "github-actions"
          # authenticated clone with GH_TOKEN
          rm -rf infra && git clone https://x-access-token:${GH_TOKEN}@github.com/${INFRA_REPO}.git infra
          cd infra
          BR=update-user-${GITHUB_SHA}
          git checkout -b ${BR}
          sed -i "s|image: .*${IMAGE}:.*|image: ${REGION}-docker.pkg.dev/${GCP_PROJECT_ID}/${REPO}/${IMAGE}:${GITHUB_SHA}|g" k8s-gcp/user-service/deployment-gcp.yaml || true
          git add k8s-gcp/user-service/deployment-gcp.yaml || true
          git commit -m "chore: user-service image ${GITHUB_SHA}" || exit 0
          git push -u origin ${BR}
          echo "${GH_TOKEN}" | gh auth login --with-token
          gh pr create --title "chore: user-service image ${GITHUB_SHA}" --body "Update image to ${GITHUB_SHA}" --repo ${INFRA_REPO}
